# Generated by Django 5.1.7 on 2026-02-07 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('history', models.IntegerField(default=0, help_text='Minutes of transmission history visible (0 = unlimited)')),
                ('is_default', models.BooleanField(default=False, help_text='Default plan for new users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TalkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_id', models.IntegerField(help_text='Talkgroup decimal ID', verbose_name='Decimal ID')),
                ('alpha_tag', models.CharField(blank=True, help_text="Short identifier (e.g., 'PD Disp')", max_length=50)),
                ('common_name', models.CharField(blank=True, help_text='Common name for display', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(default=True, help_text='If true, included in default talkgroup access')),
                ('last_transmission', models.DateTimeField(blank=True, null=True)),
                ('recent_usage', models.IntegerField(default=0, help_text='Transmission count in recent time window')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talkgroups', to='radio.system')),
            ],
            options={
                'verbose_name': 'Talk Group',
                'verbose_name_plural': 'Talk Groups',
                'ordering': ['alpha_tag'],
            },
        ),
        migrations.CreateModel(
            name='ScanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('public', models.BooleanField(default=False, help_text='Allow other users to view this scanlist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanlists', to=settings.AUTH_USER_MODEL)),
                ('talkgroups', models.ManyToManyField(blank=True, related_name='scanlists', to='radio.talkgroup')),
            ],
            options={
                'verbose_name': 'Scan List',
                'verbose_name_plural': 'Scan Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TalkGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_group', models.BooleanField(default=False, help_text='Automatically assigned to new users')),
                ('default_new_talkgroups', models.BooleanField(default=False, help_text='Automatically add new public talkgroups to this group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talkgroups', models.ManyToManyField(blank=True, related_name='access_groups', to='radio.talkgroup')),
            ],
            options={
                'verbose_name': 'Talk Group Access',
                'verbose_name_plural': 'Talk Group Access Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_unit_ids', models.BooleanField(default=True, help_text='Show unit IDs in transmission display')),
                ('is_approved', models.BooleanField(default=True, help_text='User approved for access (for closed registration)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='radio.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('talkgroup_access', models.ManyToManyField(blank=True, related_name='profiles', to='radio.talkgroupaccess')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('play_length', models.FloatField(default=0, help_text='Audio duration in seconds')),
                ('audio_file', models.CharField(help_text='Audio filename', max_length=255)),
                ('audio_file_url_path', models.CharField(blank=True, default='/', help_text='Full URL path if different from default', max_length=512)),
                ('audio_file_type', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('m4a', 'M4A')], default='mp3', max_length=10)),
                ('has_audio', models.BooleanField(default=True, help_text='Whether audio file is available')),
                ('talkgroup', models.IntegerField(help_text='Talkgroup decimal ID (preserved even if TG deleted)')),
                ('freq', models.BigIntegerField(blank=True, help_text='Transmission frequency in Hz', null=True)),
                ('emergency', models.BooleanField(default=False, help_text='Emergency transmission flag')),
                ('from_default_source', models.BooleanField(default=True, help_text='From primary recording source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='radio.system')),
                ('talkgroup_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='radio.talkgroup')),
            ],
            options={
                'verbose_name': 'Transmission',
                'verbose_name_plural': 'Transmissions',
                'ordering': ['-pk'],
                'permissions': (('download_audio', 'Can download audio clips'),),
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Transcription text content')),
                ('is_automated', models.BooleanField(default=False, help_text='True if generated by speech-to-text')),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score for automated transcriptions (0-1)', null=True)),
                ('language', models.CharField(default='en', help_text='ISO language code', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/edited transcription', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transmission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='radio.transmission')),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True, help_text='Allow public viewing of this incident')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('transmissions', models.ManyToManyField(blank=True, related_name='incidents', to='radio.transmission')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_id', models.IntegerField(help_text='Unit decimal ID', verbose_name='Decimal ID')),
                ('description', models.CharField(blank=True, help_text='Unit description or callsign', max_length=100)),
                ('unit_type', models.CharField(blank=True, choices=[('M', 'Mobile'), ('P', 'Portable'), ('B', 'Base Station'), ('D', 'Dispatch')], default='M', max_length=1)),
                ('unit_number', models.CharField(blank=True, help_text="Unit number (e.g., 'E-51', 'Car 42')", max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='radio.system')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['system', 'dec_id'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_units', to='radio.transmission')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_transmissions', to='radio.unit')),
            ],
            options={
                'verbose_name': 'Transmission Unit',
                'verbose_name_plural': 'Transmission Units',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='transmission',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='transmissions', through='radio.TransmissionUnit', to='radio.unit'),
        ),
        migrations.AddIndex(
            model_name='talkgroup',
            index=models.Index(fields=['dec_id', 'system'], name='radio_talkg_dec_id_c25da2_idx'),
        ),
        migrations.AddIndex(
            model_name='talkgroup',
            index=models.Index(fields=['slug'], name='radio_talkg_slug_a0304a_idx'),
        ),
        migrations.AddIndex(
            model_name='talkgroup',
            index=models.Index(fields=['last_transmission'], name='radio_talkg_last_tr_0da8ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='talkgroup',
            constraint=models.UniqueConstraint(fields=('dec_id', 'system'), name='unique_talkgroup_per_system'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['dec_id', 'system'], name='radio_unit_dec_id_b49f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['slug'], name='radio_unit_slug_950e5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('dec_id', 'system'), name='unique_unit_per_system'),
        ),
        migrations.AddConstraint(
            model_name='transmissionunit',
            constraint=models.UniqueConstraint(fields=('transmission', 'unit'), name='unique_unit_per_transmission'),
        ),
        migrations.AddIndex(
            model_name='transmission',
            index=models.Index(fields=['-start_datetime'], name='radio_trans_start_d_b93293_idx'),
        ),
        migrations.AddIndex(
            model_name='transmission',
            index=models.Index(fields=['system', '-start_datetime'], name='radio_trans_system__7162a6_idx'),
        ),
        migrations.AddIndex(
            model_name='transmission',
            index=models.Index(fields=['talkgroup_info', '-start_datetime'], name='radio_trans_talkgro_914ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='transmission',
            index=models.Index(fields=['emergency', '-start_datetime'], name='radio_trans_emergen_eda5c0_idx'),
        ),
    ]
