# Generated by Trunk Player v2

from django.db import migrations


def create_default_plan(apps, schema_editor):
    """Create the default plan for new users."""
    Plan = apps.get_model("radio", "Plan")
    Plan.objects.get_or_create(
        pk=1,
        defaults={
            "name": "Default",
            "description": "Default plan for all users",
            "history": 0,  # Unlimited
            "is_default": True,
        }
    )


def remove_default_plan(apps, schema_editor):
    """Remove the default plan."""
    Plan = apps.get_model("radio", "Plan")
    Plan.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_plan, remove_default_plan),
    ]
