# Generated by Django 5.1.7 on 2026-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_create_default_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_talkgroups',
            field=models.ManyToManyField(blank=True, help_text="Talkgroups shown in user's quick access dropdown", related_name='favorited_by', to='radio.talkgroup'),
        ),
    ]
